feat: ajoute l'historique de la synthèse des résultats (281)
DITP-pilotage/pilote-2 pull request #236
Opened 2023-03-27 10:28 UTC by ludc-octo

2023-03-28 13:34 UTC, Maxgux commented on src/server/infrastructure/api/chantier/[chantierId]/historiqueDeLaSynthèseDesRésultats.ts
> +    throw error;
Pourquoi on throw à nouveau ici ?

2023-03-28 13:38 UTC, Maxgux commented on src/server/usecase/synthèse/RécupérerLHistoriqueDeLaSynthèseDesRésultatsUseCase.ts
> +}
Pas de test sur ce fichier ? Ca n'a pas une valeur dingue donc ça ce challenge ;)

2023-03-28 13:40 UTC, Maxgux commented on src/server/infrastructure/accès_données/synthèseDesRésultats/SynthèseDesRésultatsSQLRepository.ts
> +  private _mapperAuDomaine(synthèse: synthese_des_resultats): SynthèseDesRésultats | null {
mapperVersDomaine ?

2023-03-28 13:40 UTC, Maxgux commented on src/server/infrastructure/accès_données/synthèseDesRésultats/SynthèseDesRésultatsSQLRepository.ts
> +    if (synthèseDesRésultats === null) {
C'est déjà fait dans le mapper

2023-03-28 14:06 UTC, ludc-octo commented on src/server/domain/synthèseDesRésultats/SynthèseDesRésultats.interface.ts
> -} | null;
C'est pour être cohérent avec le type DétailsCommentaire qui lui n'est pas nullable. Alors, j'ai hésité entre : rendre les deux types nullables ou interdire partout le nullable. Et j'ai tenté la 2e option, pour cette raison : quand un type est nullable je trouve que c'est piégeux pour la lecture du code, et qu'il faut mettre en évidence. Après ça se débat

2023-03-28 14:07 UTC, ludc-octo commented on src/server/usecase/synthèse/RécupérerLHistoriqueDeLaSynthèseDesRésultatsUseCase.ts
> +}
Exact, vu que ce n'est qu'un passe plat pour l'instant, je me suis dit que ça valait pas le coup

2023-03-28 14:08 UTC, ludc-octo commented on src/server/infrastructure/api/chantier/[chantierId]/historiqueDeLaSynthèseDesRésultats.ts
> +    throw error;
J'ai repris la même logique que pour les autres endpoints, j'imagine que c'est pour éviter de catch un erreur autre qu'une ParsingError. Je suis d'accord que ce bout de code n'est pas très élégant

2023-03-29 10:28 UTC, Maxgux requested changes

2023-03-29 10:28 UTC, Maxgux commented on src/server/infrastructure/api/chantier/[chantierId]/historiqueDeLaSynthèseDesRésultats.ts
> +    throw error;
Je pense que c'est une erreur tu peux le virer ;)

2023-03-29 10:28 UTC, Maxgux commented on src/server/usecase/synthèse/RécupérerLHistoriqueDeLaSynthèseDesRésultatsUseCase.ts
> +}
Ca me va

2023-03-29 10:28 UTC, Maxgux commented on src/server/domain/synthèseDesRésultats/SynthèseDesRésultats.interface.ts
> -} | null;
Effectivement, je ne suis pas forcément aligné. C'est la responsabilité du back de savoir si ce commentaire est "complet" et peut être considéré comme valide. 

Lorsqu'on lui demande donne moi la synthèse des resultats de ce chantier : il répond null pour dire qu'il n'y en a pas (ou qu'il est invalide) ou l'objet complet pour signifier qu'il en existe une valide. 

Ce n'est pas la responsabilité du front de décider des règles pour dire qu'une synthèse est valide.
Donc je serais pour le retour de ce | null 

Dispo pour en parler de vive voix si tu veux

2023-03-31 15:58 UTC, merged